version: '3.7'
services:
  # Django Backend
  apirest:
    ports:
      - 8000:8000
    restart: always
    env_file:
      - prod.env
    container_name: apirest_djangorf
    build:
      context: .
      dockerfile: Dockerfile
    #user: root
    depends_on:
      - database
    volumes:
      - .:/app
      - static:/static_files
    image: backend:1.0
    networks:
      - apirest-network

  # Database PostgreSQL
  database:
    image: postgres:13.3-alpine
    container_name: db_postgres
    restart: unless-stopped
    env_file:
      - prod.env
    volumes:
      - database:/var/lib/postgresql/data
      - ./api/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5430:5432
    networks:
      - apirest-network

  # pgAdmin para administración de PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pg_admin
    env_file:
      - prod.env
    ports:
      - 5050:80
    depends_on:
      - database
    networks:
      - apirest-network

  # Servidor nginx
  nginx:
    container_name: nginx
    #restart: always
    build: ./nginx
    ports:
      - 1337:80
      #- 10080:80
      #- 10443:443
    volumes:
      - static:/static_files
    depends_on:
      - apirest
    networks:
      - apirest-network

volumes:
  database:
  static:
networks:
  apirest-network:
    driver: bridge
