name: 'Deploy'
on:
  push:
    branches:
      - master # Decido que se ejecute sobre la rama principal
  #Permitir ejecutar las acciones manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #Crea el archivo de entorno para el proyecto
      - name: Create 'prod.env' file and the file for extract data
        run: |
          if [ -z "$PROD" ]; then
            echo "No found ENV variable"
            exit 1      
          fi
          echo "$PROD" > prod.env
          cat prod.env
        env:
          PROD: ${{ secrets.PROD_ENVS }}
      #Instala el CLI de Railway
      - name: Install Railway
        run: npm i -g @railway/cli
      #Deploy del proyecto ejecutando el comando especifico para crear los contenedores
      - name: Deploy
        run: |
          railway run "docker-compose up -d"
        env:
          RAILWAY_TOKEN: ${{ secrets.PROD_TOKEN }}
