name: 'Docker Containers'
#description: 'Build & check docker containers'
on:
  push:
    branches:
      - test # Actualiza esta rama según tus necesidades
  #Permitir ejecutar las acciones manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and run containers

        run: docker-compose -f "docker-compose.yml" up -d --build && docker ps

      - name: Check containers
        run: |
          RUNNING_CONTAINERS=$(docker ps | wc -l)
          if [ "$RUNNING_CONTAINERS" -eq 0 ] || [ "$RUNNING_CONTAINERS" -lt 5 ]; then
            echo "ERROR: Failed to create containers"
            exit 1
          else
            echo "SUCCESSFUL!"
            exit 0
          fi
