name: Docker Containers
description: 'Build & check docker containers on the project'
on:
  push:
    branches:
      - test # Actualiza esta rama según tus necesidades

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-cli@v1
        with:
          version: '2.0.0'

      - name: Build and run containers
        run: |
          docker-compose -f "docker-compose.yml" up -d --build
          docker ps

      - name: Check containers
        run: |
          RUNNING_CONTAINERS=$(docker-compose ps -q)
          if [ -z "$RUNNING_CONTAINERS" ]; then
            echo "ERROR: Failed to create containers"
            exit 1
          else
            echo "SUCCESSFUL!"
            exit 0
          fi
